// Per-tier system prompts and the prompt version that participates in cache keys.
//
// Changing any prompt text here MUST bump `promptVersion`, because the version is
// part of every cache key (see CLAUDE.md). Stale prompts with a fresh cache would
// otherwise serve answers generated by an older instruction.

/** Bump whenever any prompt below changes. Part of every cache key. */
export const promptVersion = 1;

/**
 * The five fixed, labelled sections of a deep-dive answer, in order. The deep
 * dive must always emit exactly these headers so the panel can render them as a
 * stable, collapsible structure.
 */
export const DEEP_DIVE_SECTIONS = [
	'What it does',
	'Inputs and outputs',
	'Side effects',
	'Edge cases',
	'Defined at',
] as const;

export interface DeepDiveTarget {
	/** Source text of the unit being explained (the enclosing function/class). */
	code: string;
	/** Language id of the source, e.g. `typescript`. */
	languageId: string;
	/** Assembled supporting context: signatures, referenced definitions, etc. */
	context?: string;
}

function sectionHeader(title: string): string {
	return `## ${title}`;
}

/**
 * Build the deep-dive prompt. The instruction pins the answer to the five fixed
 * section headers in {@link DEEP_DIVE_SECTIONS}; the failure mode is padding, so
 * the prompt constrains against preamble and filler.
 */
export function buildDeepDivePrompt(target: DeepDiveTarget): string {
	const headers = DEEP_DIVE_SECTIONS.map(sectionHeader).join('\n');

	const parts = [
		'You are explaining a single unit of code for an experienced engineer.',
		'Answer using EXACTLY these five Markdown section headers, in this order,',
		'and nothing else — no preamble, no closing remarks, no extra sections:',
		'',
		headers,
		'',
		'Keep each section tight and concrete. If a section does not apply, write',
		'"None" under it rather than omitting the header. Under "Defined at", list',
		'where referenced symbols are defined when that information is available.',
		'',
		`Language: ${target.languageId}`,
	];

	if (target.context && target.context.trim().length > 0) {
		parts.push('', 'Supporting context:', '```', target.context, '```');
	}

	parts.push('', 'Code to explain:', '```' + target.languageId, target.code, '```');

	return parts.join('\n');
}
